services:
  - type: web
    name: ai-detector-fastapi
    env: Python 3
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn chatbot_api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
