PINECONE_API_KEY = "pcsk_3562qp_NjYv6nGhcw3GXj5r5f9jJAULgyJMCh9EXis1pwfbPgfgiaHzUDQgUUAir7Gu53K"
GOOGLE_API_KEY = "AIzaSyCV7zALZ3mL-ZG8y9yCI3TIsV4Va9DJg0A"
PINECONE_CLOUD = "aws"
PINECONE_REGION = "us-east-1"
HF_TOKEN = "your hf token "
